Repository pc-codingavision/palermo-fe-final-project, pull requests merged in 2020-10, with the labels that each got.

#5 feature/skeleton-angular-project
  .browserslistrc
  .editorconfig
  .gitignore
  README.md
  angular.json
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/assets/.gitkeep
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/main.ts
  src/polyfills.ts
  src/styles.scss
  src/test.ts
  tsconfig.app.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.spec.json
  tslint.json
Labels: code review

#37 Remove e2e test execution.
  .circleci/config.yml
  e2e/protractor.conf.js
Labels: code review

#31 Feature/#11 angular material
  src/app/app.module.ts
  src/app/shared/libraries/material/material.module.ts
Labels: code review

#39 Feature/manager/#14 tenant
  src/app/modules/core/manager/manager-routing.module.ts
  src/app/modules/core/manager/manager.module.ts
  src/app/modules/core/manager/tenant/edit/edit.component.html
  src/app/modules/core/manager/tenant/edit/edit.component.scss
  src/app/modules/core/manager/tenant/edit/edit.component.spec.ts
  src/app/modules/core/manager/tenant/edit/edit.component.ts
  src/app/modules/core/manager/tenant/list/list.component.html
  src/app/modules/core/manager/tenant/list/list.component.scss
  src/app/modules/core/manager/tenant/list/list.component.spec.ts
  src/app/modules/core/manager/tenant/list/list.component.ts
  src/app/modules/core/manager/tenant/tenant-routing.module.ts
  src/app/modules/core/manager/tenant/tenant.module.ts
  src/app/modules/core/manager/tenant/view/view.component.html
  src/app/modules/core/manager/tenant/view/view.component.scss
  src/app/modules/core/manager/tenant/view/view.component.spec.ts
  src/app/modules/core/manager/tenant/view/view.component.ts
Labels: enhancement

#40 Feature/manager/#13 landlord
  src/app/modules/core/manager/landlord/edit/edit.component.html
  src/app/modules/core/manager/landlord/edit/edit.component.scss
  src/app/modules/core/manager/landlord/edit/edit.component.spec.ts
  src/app/modules/core/manager/landlord/edit/edit.component.ts
  src/app/modules/core/manager/landlord/landlord-routing.module.ts
  src/app/modules/core/manager/landlord/landlord.module.ts
  src/app/modules/core/manager/landlord/list/list.component.html
  src/app/modules/core/manager/landlord/list/list.component.scss
  src/app/modules/core/manager/landlord/list/list.component.spec.ts
  src/app/modules/core/manager/landlord/list/list.component.ts
  src/app/modules/core/manager/landlord/new/new.component.html
  src/app/modules/core/manager/landlord/new/new.component.scss
  src/app/modules/core/manager/landlord/new/new.component.spec.ts
  src/app/modules/core/manager/landlord/new/new.component.ts
  src/app/modules/core/manager/landlord/view/view.component.html
  src/app/modules/core/manager/landlord/view/view.component.scss
  src/app/modules/core/manager/landlord/view/view.component.spec.ts
  src/app/modules/core/manager/landlord/view/view.component.ts
  src/app/modules/core/manager/manager-routing.module.ts
  src/app/modules/core/manager/manager.module.ts
Labels: enhancement

#38 Feature/manager/#15 reservation
  src/app/modules/core/manager/manager-routing.module.ts
  src/app/modules/core/manager/manager.module.ts
  src/app/modules/core/manager/reservation/details/details.component.html
  src/app/modules/core/manager/reservation/details/details.component.scss
  src/app/modules/core/manager/reservation/details/details.component.spec.ts
  src/app/modules/core/manager/reservation/details/details.component.ts
  src/app/modules/core/manager/reservation/list/list.component.html
  src/app/modules/core/manager/reservation/list/list.component.scss
  src/app/modules/core/manager/reservation/list/list.component.spec.ts
  src/app/modules/core/manager/reservation/list/list.component.ts
  src/app/modules/core/manager/reservation/reservation-routing.module.ts
  src/app/modules/core/manager/reservation/reservation.module.ts
Labels: enhancement

#56 Bugfix/material module
  src/app/app.module.ts
  src/app/shared/material.module.ts
Labels: bug

#58 Feature/#21 tenant/profile routing
  documentation/images/site-map/advertisement-level.png
  documentation/images/site-map/landlord-level.png
  documentation/images/site-map/landlord-profile-level.png
  documentation/images/site-map/landlord-real-estate-level.png
  documentation/images/site-map/manager-landlord-level.png
  documentation/images/site-map/manager-level.png
  documentation/images/site-map/manager-reservation-level.png
  documentation/images/site-map/manager-tenant-level.png
  documentation/images/site-map/root-level.png
  documentation/images/site-map/tenant-level.png
  documentation/images/site-map/tenant-profile-level.png
  documentation/images/site-map/tenant-reservation-level.png
  src/app/app.module.ts
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.html
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.scss
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.spec.ts
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.ts
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.html
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.scss
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.spec.ts
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.ts
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.html
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.scss
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.spec.ts
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.ts
  src/app/modules/core/tenant/profile/profile.module.ts
  src/app/shared/material.module.ts
Labels: code review

#42 created reservation-container-component
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.html
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.scss
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.spec.ts
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.ts
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.html
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.scss
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.spec.ts
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.ts
  src/app/modules/core/tenant/reservation/reservation-routing.module.ts
  src/app/modules/core/tenant/reservation/reservation.module.ts
  src/app/modules/core/tenant/tenant-routing.module.ts
Labels: code review

#59 Feature/#17 landlord/profile routing
  .circleci/config.yml
  documentation/images/site-map/advertisement-level.png
  documentation/images/site-map/landlord-level.png
  documentation/images/site-map/landlord-profile-level.png
  documentation/images/site-map/landlord-real-estate-level.png
  documentation/images/site-map/manager-landlord-level.png
  documentation/images/site-map/manager-level.png
  documentation/images/site-map/manager-reservation-level.png
  documentation/images/site-map/manager-tenant-level.png
  documentation/images/site-map/root-level.png
  documentation/images/site-map/tenant-level.png
  documentation/images/site-map/tenant-profile-level.png
  documentation/images/site-map/tenant-reservation-level.png
  e2e/protractor.conf.js
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.html
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.scss
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.spec.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.html
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.scss
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.spec.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.html
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.scss
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.spec.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.ts
  src/app/modules/core/landlord/landlord-profile/landlord-profile-routing.module.ts
  src/app/modules/core/landlord/landlord-profile/landlord-profile.module.ts
  src/app/modules/core/landlord/landlord-routing.module.ts
  src/app/modules/core/landlord/landlord.module.ts
  src/app/modules/core/landlord/profile/edit/edit.component.spec.ts
  src/app/modules/core/landlord/profile/edit/edit.component.ts
  src/app/modules/core/landlord/profile/profile-routing.module.ts
  src/app/modules/core/landlord/profile/profile.module.ts
  src/app/modules/core/landlord/profile/view/view.component.spec.ts
  src/app/modules/core/landlord/profile/view/view.component.ts
  src/app/modules/core/package.info
  src/app/shared/material.module.ts
Labels: code review

#57 Feature/#18 landlord/realestate routing
  src/app/modules/core/landlord/landlord-routing.module.ts
  src/app/modules/core/landlord/landlord.module.ts
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.html
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.ts
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.html
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.ts
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.html
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.ts
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.html
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.ts
  src/app/modules/core/landlord/realestate/realestate-routing.module.ts
  src/app/modules/core/landlord/realestate/realestate.module.ts
Labels: code review

#60 Feature/#19 tenant routing
  src/app/app-routing.module.ts
  src/app/modules/core/package.info
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.html
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.scss
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.spec.ts
  src/app/modules/core/tenant/profile/components/profile-container/profile-container.component.ts
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.html
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.scss
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.spec.ts
  src/app/modules/core/tenant/profile/components/profile-edit/profile-edit.component.ts
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.html
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.scss
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.spec.ts
  src/app/modules/core/tenant/profile/components/profile-view/profile-view.component.ts
  src/app/modules/core/tenant/profile/profile-routing.module.ts
  src/app/modules/core/tenant/profile/profile.module.ts
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.html
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.scss
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.spec.ts
  src/app/modules/core/tenant/reservation/components/reservation-container/reservation-container.component.ts
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.html
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.scss
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.spec.ts
  src/app/modules/core/tenant/reservation/components/reservation-list/reservation-list.component.ts
  src/app/modules/core/tenant/reservation/reservation-routing.module.ts
  src/app/modules/core/tenant/reservation/reservation.module.ts
  src/app/modules/core/tenant/tenant-routing.module.ts
  src/app/modules/core/tenant/tenant.module.ts
Labels: code review

#61 Feature/#16 landlord routing
  src/app/app-routing.module.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.html
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.scss
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.spec.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-container/landlord-profile-container.component.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.html
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.scss
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.spec.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.html
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.scss
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.spec.ts
  src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.ts
  src/app/modules/core/landlord/landlord-profile/landlord-profile-routing.module.ts
  src/app/modules/core/landlord/landlord-profile/landlord-profile.module.ts
  src/app/modules/core/landlord/landlord-routing.module.ts
  src/app/modules/core/landlord/landlord.module.ts
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.html
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-add/realestate-add.component.ts
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.html
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-container/realestate-container.component.ts
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.html
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-edit/realestate-edit.component.ts
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.html
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.scss
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.spec.ts
  src/app/modules/core/landlord/realestate/components/realestate-list/realestate-list.component.ts
  src/app/modules/core/landlord/realestate/realestate-routing.module.ts
  src/app/modules/core/landlord/realestate/realestate.module.ts
Labels: code review

#69 Feature/#62 Page not found component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/shared/components/pagenotfound/pagenotfound.component.html
  src/app/shared/components/pagenotfound/pagenotfound.component.scss
  src/app/shared/components/pagenotfound/pagenotfound.component.spec.ts
  src/app/shared/components/pagenotfound/pagenotfound.component.ts
Labels: enhancement

#75 Feature/#23 create routing for advertisment/list
  src/app/modules/core/advertisment/advertisment-routing.module.ts
  src/app/modules/core/advertisment/advertisment.module.ts
  src/app/modules/core/advertisment/components/advertisment-container/advertisment-container.component.html
  src/app/modules/core/advertisment/components/advertisment-container/advertisment-container.component.scss
  src/app/modules/core/advertisment/components/advertisment-container/advertisment-container.component.spec.ts
  src/app/modules/core/advertisment/components/advertisment-container/advertisment-container.component.ts
  src/app/modules/core/advertisment/components/advertisment-list/advertisment-list.component.html
  src/app/modules/core/advertisment/components/advertisment-list/advertisment-list.component.scss
  src/app/modules/core/advertisment/components/advertisment-list/advertisment-list.component.spec.ts
  src/app/modules/core/advertisment/components/advertisment-list/advertisment-list.component.ts
  src/index.html
  src/styles.scss
Labels: code review

#79 add advertisment-details.component with routing
  src/app/modules/core/advertisment/advertisment-routing.module.ts
  src/app/modules/core/advertisment/advertisment.module.ts
  src/app/modules/core/advertisment/components/advertisment-details/advertisment-details.component.html
  src/app/modules/core/advertisment/components/advertisment-details/advertisment-details.component.scss
  src/app/modules/core/advertisment/components/advertisment-details/advertisment-details.component.spec.ts
  src/app/modules/core/advertisment/components/advertisment-details/advertisment-details.component.ts
Labels: code review

#82 Add git pre-commit hook.
  package-lock.json
  package.json
Labels: enhancement

#81 Feature/#22 brainstorming the router setup for the advertisment feature
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/modules/core/advertisement/advertisement-routing.module.ts
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.html
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.scss
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.html
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.ts
  src/index.html
  src/styles.scss
Labels: code review

#68 Feature/#48 reservation model
  src/app/shared/enum/role.ts
  src/app/shared/models/mock-data/mock-reservation.ts
  src/app/shared/models/package.info
  src/app/shared/models/reservation.ts
Labels: code review

#67 Feature/#50 models for property
  src/app/shared/enum/category.ts
  src/app/shared/enum/status.ts
  src/app/shared/enum/toilet.ts
  src/app/shared/mock-data/mock-property.ts
  src/app/shared/models/property.ts
Labels: code review

#80 Feature/#49 advertisement model
  src/app/shared/enum/role.ts
  src/app/shared/models/advertisement.ts
  src/app/shared/models/mock-data/mock-advertisement.ts
Labels: code review

#76 Feature/#45 manager entity
  src/app/shared/enum/phonetype.ts
  src/app/shared/enum/role.ts
  src/app/shared/models/manager.ts
  src/app/shared/models/mock-data/mock-manager.ts
  src/app/shared/models/users.ts
Labels: code review

#77 Feature/#46 landlord entity
  src/app/shared/models/landlord.ts
  src/app/shared/models/mock-data/mock-landlord.ts
Labels: code review

#88 Feature/#83 refactoring mock data
  src/app/shared/enum/category.ts
  src/app/shared/enum/status.ts
  src/app/shared/models/mock-data/mock-advertisement.ts
  src/app/shared/models/mock-data/mock-property.ts
  src/app/shared/models/mock-data/mock-reservation.ts
  src/app/shared/models/property.ts
  src/app/shared/models/users.ts
Labels: code review

#94 Feature/#91 advertisement sidebar ui
  angular.json
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.html
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/facility-filter/facility-filter.component.html
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/facility-filter/facility-filter.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/facility-filter/facility-filter.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/facility-filter/facility-filter.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/price-filter/price-filter.component.html
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/price-filter/price-filter.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/price-filter/price-filter.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/price-filter/price-filter.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/score-filter/score-filter.component.html
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/score-filter/score-filter.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/score-filter/score-filter.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/score-filter/score-filter.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/sidebar-container.component.html
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/sidebar-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/sidebar-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/sidebar-container/sidebar-container.component.ts
  src/app/modules/shared/material.module.ts
Labels: enhancement

#96 Feature/#92 card main view
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-container.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-container.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/book-button/book-button.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/book-button/book-button.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/book-button/book-button.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/book-button/book-button.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/card-main-view.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/card-main-view.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/card-main-view.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/card-main-view.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/dates/dates.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/dates/dates.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/dates/dates.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/dates/dates.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facilities-container.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facilities-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facilities-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facilities-container.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facility/facility.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facility/facility.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facility/facility.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/facilities-container/facility/facility.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/favourite/favourite.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/favourite/favourite.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/favourite/favourite.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/favourite/favourite.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/photogallery/photogallery.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/photogallery/photogallery.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/photogallery/photogallery.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/photogallery/photogallery.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/score/score.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/score/score.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/score/score.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/card-container/card-main-view/score/score.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/properties-container.component.html
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/properties-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/properties-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/properties-container/properties-container.component.ts
  src/app/modules/shared/material.module.ts
Labels: enhancement

#99 Fixed mock-data advertisement
  src/app/shared/models/advertisement.ts
  src/app/shared/models/mock-data/mock-advertisement.ts
Labels: bug

#100 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#111 Refactoring/components latest
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.html
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-mini-card/latest-mini-card.component.html
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-mini-card/latest-mini-card.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-mini-card/latest-mini-card.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-mini-card/latest-mini-card.component.ts
Labels: code review

#102 Feature/#44 authentication and authorization
  documentation/auth-hierarchy.drawio
  documentation/images/doc/auth-hierarchy.png
  e2e/tsconfig.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/modules/core/auth/auth-in-memory.service.ts
  src/app/modules/core/auth/auth.module.ts
  src/app/modules/core/auth/auth.service.spec.ts
  src/app/modules/core/auth/auth.service.ts
  src/app/modules/core/auth/cache.service.ts
  src/app/modules/core/auth/models/user.ts
  src/app/shared/common.ts
  src/app/shared/models/role.enum.ts
  src/app/shared/models/tenant.ts
  tsconfig.app.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.spec.json
Labels: code review

#106 Feature/issue 71 implement logout
  .gitignore
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/shared/components/logout/logout.component.html
  src/app/shared/components/logout/logout.component.scss
  src/app/shared/components/logout/logout.component.spec.ts
  src/app/shared/components/logout/logout.component.ts
Labels: code review
