Repository pc-codingavision/palermo-fe-final-project, pull requests merged in 2020-11, with the labels that each got.

#120 Feature/issue 73 implement http interceptor to manage jwt token
  debug.log
  src/app/app.module.ts
  src/app/modules/core/auth/auth-http-interceptor.spec.ts
  src/app/modules/core/auth/auth-http-interceptor.ts
Labels: code review

#121 Feature/issue 74 implement the login component
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/shared/common.testing.ts
  src/app/shared/components/login/login.component.html
  src/app/shared/components/login/login.component.spec.ts
  src/app/shared/components/login/login.component.ts
Labels: code review

#125 Created shared module
  src/app/app.module.ts
  src/app/modules/shared/shared.module.ts
Labels: code review

#122 Bugfix/issue 117 bugfix in folder advertisement
  src/app/modules/core/advertisement/advertisement-routing.module.ts
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/card-main-view.component.html
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.html
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/datapicker/datapicker.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/facilities-container/facilities-container.component.html
Labels: code review

#108 Added dialog service, dialog component and DialogData interface
  src/app/app.module.ts
  src/app/modules/shared/material.module.ts
  src/app/shared/components/dialog/dialog.component.html
  src/app/shared/components/dialog/dialog.component.scss
  src/app/shared/components/dialog/dialog.component.spec.ts
  src/app/shared/components/dialog/dialog.component.ts
  src/app/shared/models/dialog-data.ts
  src/app/shared/services/dialog.service.spec.ts
  src/app/shared/services/dialog.service.ts
Labels: enhancement

#126 Feature/issue 118 create the main toolbar
  src/app/shared/common.testing.ts
  src/app/shared/components/toolbar/toolbar.component.html
  src/app/shared/components/toolbar/toolbar.component.scss
  src/app/shared/components/toolbar/toolbar.component.spec.ts
  src/app/shared/components/toolbar/toolbar.component.ts
  src/styles.scss
Labels: code review

#127 Feature/issue 119 navigation sidenav
  angular.json
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/card-extra.component.scss
  src/app/modules/core/landlord/landlord-routing.module.ts
  src/app/modules/shared/material.module.ts
  src/app/shared/components/navigation-menu/navigation-menu.component.scss
  src/app/shared/components/navigation-menu/navigation-menu.component.spec.ts
  src/app/shared/components/navigation-menu/navigation-menu.component.ts
  src/app/shared/components/sidenav/sidenav.component.html
  src/app/shared/components/sidenav/sidenav.component.scss
  src/app/shared/components/sidenav/sidenav.component.spec.ts
  src/app/shared/components/sidenav/sidenav.component.ts
Labels: code review

#133 Add landlord service and test
  src/app/modules/shared/services/landlord/landlord.service.spec.ts
  src/app/modules/shared/services/landlord/landlord.service.ts
Labels: code review

#129 Move dialog component in the shared module
  src/app/app.module.ts
  src/app/modules/shared/shared.module.ts
Labels: bug

#132 add mock-advertisement.ts
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
Labels: code review

#135 refactoring style
  src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/about/about.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/card-extra.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/facilities/facilities.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/card-main-view.component.html
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/card-main-view.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/facilities-container/facility/facility.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/score/score.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar/facility-filter/facility-filter.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar/price-filter/price-filter.component.scss
  src/app/modules/core/advertisement/components/advertisement-list/sidebar/score-filter/score-filter.component.scss
Labels: code review

#137 Feature/issue 134 create landlord list
  package-lock.json
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.ts
  src/app/modules/core/manager/components/container/manager-container.component.html
  src/app/modules/core/manager/components/container/manager-container.component.scss
  src/app/modules/core/manager/landlord/components/container/landlord-container.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.scss
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
  src/app/modules/core/manager/landlord/components/search/search.component.html
  src/app/modules/core/manager/landlord/components/search/search.component.scss
  src/app/modules/core/manager/landlord/components/search/search.component.spec.ts
  src/app/modules/core/manager/landlord/components/search/search.component.ts
  src/app/modules/core/manager/landlord/components/view/components/address/address.component.html
  src/app/modules/core/manager/landlord/components/view/components/address/address.component.scss
  src/app/modules/core/manager/landlord/components/view/components/address/address.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/components/address/address.component.ts
  src/app/modules/core/manager/landlord/components/view/components/button-container/button-container.component.html
  src/app/modules/core/manager/landlord/components/view/components/button-container/button-container.component.scss
  src/app/modules/core/manager/landlord/components/view/components/button-container/button-container.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/components/button-container/button-container.component.ts
  src/app/modules/core/manager/landlord/components/view/components/contact/contact.component.html
  src/app/modules/core/manager/landlord/components/view/components/contact/contact.component.scss
  src/app/modules/core/manager/landlord/components/view/components/contact/contact.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/components/contact/contact.component.ts
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.html
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.scss
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.ts
  src/app/modules/core/manager/landlord/components/view/components/phone/phone.component.html
  src/app/modules/core/manager/landlord/components/view/components/phone/phone.component.scss
  src/app/modules/core/manager/landlord/components/view/components/phone/phone.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/components/phone/phone.component.ts
  src/app/modules/core/manager/landlord/components/view/components/status/status.component.html
  src/app/modules/core/manager/landlord/components/view/components/status/status.component.scss
  src/app/modules/core/manager/landlord/components/view/components/status/status.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/components/status/status.component.ts
  src/app/modules/core/manager/landlord/components/view/landlord-view.component.html
  src/app/modules/core/manager/landlord/components/view/landlord-view.component.scss
  src/app/modules/core/manager/landlord/components/view/landlord-view.component.spec.ts
  src/app/modules/core/manager/landlord/components/view/landlord-view.component.ts
  src/app/modules/core/manager/landlord/landlord-routing.module.ts
  src/app/modules/core/manager/landlord/landlord.module.ts
  src/app/modules/core/manager/manager.module.ts
  src/app/modules/shared/material.module.ts
  src/app/shared/components/dialog/dialog.component.spec.ts
  src/app/shared/models/landlord.ts
  src/app/shared/models/manager.ts
  src/app/shared/models/mock-data/data.ts
  src/app/shared/models/tenant.ts
  src/app/shared/services/dialog.service.spec.ts
Labels: code review

#144 Implemented snackbar service
  src/app/modules/shared/material.module.ts
  src/app/shared/services/snack-bar.service.spec.ts
  src/app/shared/services/snack-bar.service.ts
Labels: code review

#146 feature/#145-fix getById method and test
  src/app/modules/shared/services/landlord/landlord.service.spec.ts
  src/app/modules/shared/services/landlord/landlord.service.ts
Labels: code review

#147 Feature/issue 115 create the functionality for the latest advertisement
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/advertisement.service.spec.ts
  src/app/modules/core/advertisement/advertisement.service.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.html
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/latest/latest-mini-card/latest-mini-card.component.html
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.scss
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.spec.ts
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.ts
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.html
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.scss
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.spec.ts
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.ts
Labels: code review

#149 Feature/issue 109 create ui for manager landlord edit
  src/app/app-routing.module.ts
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.html
  src/app/modules/core/landlord/landlord.module.ts
  src/app/modules/core/manager/landlord/components/edit/edit.component.html
  src/app/modules/core/manager/landlord/components/edit/edit.component.scss
  src/app/modules/core/manager/landlord/components/edit/edit.component.spec.ts
  src/app/modules/core/manager/landlord/components/edit/edit.component.ts
  src/app/modules/core/manager/landlord/components/edit/landlord-edit.component.html
  src/app/modules/core/manager/landlord/components/edit/landlord-edit.component.scss
  src/app/modules/core/manager/landlord/components/edit/landlord-edit.component.spec.ts
  src/app/modules/core/manager/landlord/components/edit/landlord-edit.component.ts
  src/app/modules/core/manager/landlord/landlord-routing.module.ts
  src/app/modules/core/manager/landlord/landlord.module.ts
  src/app/modules/shared/material.module.ts
  src/app/modules/shared/services/landlord/landlord.service.spec.ts
  src/app/modules/shared/services/landlord/landlord.service.ts
  src/app/shared/models/landlord.ts
  src/app/shared/services/deactivate-guard.service.spec.ts
  src/app/shared/services/deactivate-guard.service.ts
  src/app/shared/services/dialog.service.spec.ts
  src/app/shared/services/package.info
Labels: code review

#170 Feature/issue 161 in memory web api setup
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/shared/services/in-memory-data.service.spec.ts
  src/app/shared/services/in-memory-data.service.ts
Labels: code review

#178 Issue 142 rework filters
  src/app/modules/core/advertisement/advertisement.service.spec.ts
  src/app/modules/core/advertisement/advertisement.service.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/components/sidebar/facility-filter/facility-filter.component.ts
  src/app/modules/core/advertisement/components/sidebar/price-filter/price-filter.component.html
  src/app/modules/core/advertisement/components/sidebar/price-filter/price-filter.component.scss
  src/app/modules/core/advertisement/components/sidebar/price-filter/price-filter.component.ts
  src/app/modules/core/advertisement/components/sidebar/score-filter/score-filter.component.html
  src/app/modules/core/advertisement/components/sidebar/score-filter/score-filter.component.scss
  src/app/modules/core/advertisement/components/sidebar/score-filter/score-filter.component.ts
  src/app/modules/core/advertisement/components/sidebar/sidebar-container/sidebar-container.component.html
  src/app/modules/core/advertisement/components/sidebar/sidebar-container/sidebar-container.component.ts
  src/app/modules/core/advertisement/services/sidebar.service.spec.ts
  src/app/modules/core/advertisement/services/sidebar.service.ts
  src/app/modules/shared/shared.module.ts
  src/app/shared/models/property.ts
Labels: Refactoring

#166 Feature/issue 164 manager/tenant service
  src/app/modules/shared/interfaces/i-generic-user-service.ts
  src/app/modules/shared/services/generic-user-service.ts
  src/app/modules/shared/services/tenant/tenant.service.spec.ts
  src/app/modules/shared/services/tenant/tenant.service.ts
Labels: code review

#163 Feature/issue 148 search functionality second approach
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
  src/app/modules/core/manager/landlord/components/search/search.component.html
  src/app/modules/core/manager/landlord/components/search/search.component.ts
  src/app/modules/core/manager/landlord/services/search.service.spec.ts
  src/app/modules/core/manager/landlord/services/search.service.ts
  src/app/shared/models/mock-data/data.ts
  tsconfig.json
Labels: code review

#168 Feature/issue 160 manager landord responsive
  .vscode/settings.json
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.scss
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
  src/app/modules/core/manager/landlord/components/search/search.component.html
  src/app/modules/core/manager/landlord/components/search/search.component.scss
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.html
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.scss
Labels: code review

#169 Feature/issue 162 progress spinner service
  package-lock.json
  src/app/app.component.html
  src/app/modules/shared/material.module.ts
  src/app/modules/shared/shared.module.ts
  src/app/shared/components/spinner/spinner.component.html
  src/app/shared/components/spinner/spinner.component.scss
  src/app/shared/components/spinner/spinner.component.spec.ts
  src/app/shared/components/spinner/spinner.component.ts
  src/app/shared/services/spinner.service.spec.ts
  src/app/shared/services/spinner.service.ts
Labels: code review

#181 Issue 140 refactor score component
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.ts
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
  src/app/modules/core/advertisement/components/card/card-top/score/score.component.html
  src/app/modules/core/advertisement/components/card/card-top/score/score.component.scss
  src/app/modules/core/advertisement/components/card/card-top/score/score.component.ts
  src/app/shared/enum/enums.ts
  src/app/shared/models/advertisement.ts
Labels: code review

#165 Feature/issue 158 add a resolve guard for the advertisement list page
  package-lock.json
  src/app/modules/core/advertisement/advertisement-routing.module.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/services/advertisement-resolver.service.spec.ts
  src/app/modules/core/advertisement/services/advertisement-resolver.ts
Labels: code review
