Repository pc-codingavision/palermo-fe-final-project, pull requests merged in 2020-12, with the labels that each got.

#199 Fix bug Manager/Landlord Add and Edit
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
Labels: bug

#193 Feature/issue 189 manager/landlord add button
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.scss
Labels: enhancement

#191 Bugfix/issue 184 check in component validation issue
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.html
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.ts
Labels: bug

#180 Feature/issue 177 slideshow images in the advertisement card
  package-lock.json
  package.json
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/photogallery/photogallery.component.html
  src/app/modules/core/advertisement/components/card/card-top/photogallery/photogallery.component.ts
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.html
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.scss
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.ts
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
  src/app/modules/shared/shared.module.ts
  src/app/shared/models/mock-data/data.ts
  src/app/shared/models/property.ts
Labels: code review

#179 Fixed UI layout for advertisement list container
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.scss
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.scss
Labels: code review

#192 Feature/issue 185 most recent reviews should show no more than 3 reviews
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.spec.ts
  src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.ts
  src/app/modules/core/advertisement/components/card/card-bottom/review-dialog/review-dialog.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/review-dialog/review-dialog.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/review-dialog/review-dialog.component.spec.ts
  src/app/modules/core/advertisement/components/card/card-bottom/review-dialog/review-dialog.component.ts
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.ts
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
  src/app/shared/models/advertisement.ts
  src/app/shared/models/mock-data/data.ts
  src/app/shared/services/dialog.service.ts
Labels: code review

#190 Added support for landlord data, added tests
  src/app/shared/services/in-memory-data.service.spec.ts
  src/app/shared/services/in-memory-data.service.ts
Labels: enhancement

#202 Feature/issue 196 in memory web api add support for the reservation entity
  src/app/shared/services/in-memory-data.service.spec.ts
  src/app/shared/services/in-memory-data.service.ts
Labels: enhancement

#207 Feature/issue 197 create a service to manage reservations
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/shared/services/reservation/reservation.service.spec.ts
  src/app/modules/shared/services/reservation/reservation.service.ts
Labels: enhancement

#205 Feature/issue 187 create a cleanable input text
  src/app/modules/core/manager/landlord/components/edit/edit.component.html
  src/app/modules/core/manager/landlord/components/edit/edit.component.scss
  src/app/modules/core/manager/landlord/components/search/search.component.html
  src/app/shared/components/login/login.component.html
Labels: code review

#209 Feature/issue 157 integrate the auth mechanism with the current list of users
  src/app/app.component.spec.ts
  src/app/modules/core/auth/auth-in-memory.service.ts
  src/app/modules/core/auth/auth.service.spec.ts
  src/app/modules/core/auth/auth.service.ts
  src/app/modules/core/auth/models/user.ts
  src/app/shared/components/login/login.component.spec.ts
  src/app/shared/components/login/login.component.ts
  src/app/shared/components/navigation-menu/navigation-menu.component.spec.ts
  src/app/shared/components/package.info
  src/app/shared/components/toolbar/toolbar.component.html
  src/app/shared/components/toolbar/toolbar.component.spec.ts
  src/app/shared/models/mock-data/data.ts
  src/app/shared/models/users.ts
Labels: code review

#212 Feature/issue 200 add tenant support to the in memory web api
  src/app/shared/services/in-memory-data.service.ts
Labels: enhancement

#167 Feature/issue 159 add a resolve guard for the manager/landlord list page
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.spec.ts
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
  src/app/modules/core/manager/landlord/guards/landlord-list-resolve.ts
  src/app/modules/core/manager/landlord/landlord-routing.module.ts
  src/app/package-lock.json
Labels: enhancement

#213 Bugfix/issue 204 advertisment list UI issue
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.html
  src/app/modules/core/advertisement/components/advertisement-list/advertisement-list.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/about/about.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/about/about.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/facilities/facilities.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/facilities/facilities.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/review-dialog/review-dialog.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/review-dialog/review-dialog.component.scss
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.html
  src/app/modules/core/advertisement/components/card/card-bottom/review/review.component.scss
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.scss
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.html
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.scss
  src/app/modules/core/advertisement/components/card/card-top/facility/facility.component.html
  src/app/modules/core/advertisement/components/card/card-top/favourite/favourite.component.html
  src/app/modules/core/advertisement/components/card/card-top/favourite/favourite.component.scss
  src/app/modules/core/advertisement/components/card/card-top/photogallery/photogallery.component.html
  src/app/modules/core/advertisement/components/card/card-top/photogallery/photogallery.component.scss
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.scss
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.html
  src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.scss
  src/app/modules/core/advertisement/components/sidebar/facility-filter/facility-filter.component.html
  src/app/modules/core/advertisement/components/sidebar/facility-filter/facility-filter.component.scss
  src/app/modules/core/advertisement/components/sidebar/facility-filter/facility-filter.component.ts
  src/app/modules/core/advertisement/components/sidebar/price-filter/price-filter.component.html
  src/app/modules/core/advertisement/components/sidebar/price-filter/price-filter.component.scss
  src/app/modules/core/advertisement/components/sidebar/score-filter/score-filter.component.html
  src/app/modules/core/advertisement/components/sidebar/score-filter/score-filter.component.scss
  src/app/modules/core/advertisement/components/sidebar/sidebar-container/sidebar-container.component.html
  src/app/modules/core/advertisement/components/sidebar/sidebar-container/sidebar-container.component.scss
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
Labels: Refactoring, bug

#203 Feature/issue 188 enhance manager/landlord table
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.scss
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
  src/app/modules/core/manager/landlord/services/search.service.ts
  src/app/modules/shared/material.module.ts
  src/app/modules/shared/services/landlord/landlord.service.spec.ts
  src/app/modules/shared/services/landlord/landlord.service.ts
Labels: code review

#214 Feature/issue 201 create a tenant service
  src/app/modules/core/manager/tenant/components/container/tenant-container.component.spec.ts
  src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
  src/app/modules/shared/services/tenant/in-memory-tenant.service.ts
  src/app/shared/services/in-memory-data.service.ts
Labels: enhancement

#220 Feature/issue 175 tenant tenant list
  src/app/modules/core/manager/tenant/components/container/tenant-container.component.html
  src/app/modules/core/manager/tenant/components/container/tenant-container.component.spec.ts
  src/app/modules/core/manager/tenant/components/container/tenant-container.component.ts
  src/app/modules/core/manager/tenant/components/list/tenant-list.component.html
  src/app/modules/core/manager/tenant/components/list/tenant-list.component.scss
  src/app/modules/core/manager/tenant/components/list/tenant-list.component.ts
  src/app/modules/core/manager/tenant/tenant.module.ts
Labels: code review

#219 Feature/issue 215 improve the lastest advertisement component
  src/app/modules/core/advertisement/advertisement.service.spec.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.ts
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
Labels: Refactoring, enhancement

#217 Feature/issue 171 refactor the advertisement service to use the in memory web api for the advertisements
  src/app/modules/core/advertisement/advertisement.service.spec.ts
  src/app/modules/core/advertisement/advertisement.service.ts
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.spec.ts
  src/app/modules/core/advertisement/services/advertisement-resolver.service.spec.ts
  src/app/shared/services/in-memory-data.service.spec.ts
  src/app/shared/services/in-memory-data.service.ts
Labels: code review

#221 Feature/issue 211 refactor the check in/check out of the advertisement list
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.ts
  src/app/modules/core/advertisement/services/check-in-check-out.service.spec.ts
  src/app/modules/core/advertisement/services/check-in-check-out.service.ts
  src/app/shared/models/mock-data/data.ts
Labels: code review

#229 Fix date format in Italian
  src/app/modules/core/advertisement/advertisement.module.ts
Labels: bug

#227 Feature/issue 222 add reset to the date picker
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.html
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.scss
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/services/check-in-check-out.service.spec.ts
  src/app/modules/core/advertisement/services/check-in-check-out.service.ts
Labels: code review

#228 Add price in advertisements
  src/app/app.module.ts
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
Labels: code review

#230 Implemented advertisement-details view
  src/app/modules/core/advertisement/advertisement-routing.module.ts
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.html
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.spec.ts
  src/app/modules/core/advertisement/components/advertisement-details/advertisement-details.component.ts
  src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.scss
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
Labels: enhancement

#231 Feature/issue 225 allow booking reservation
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.spec.ts
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.html
  src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.ts
  src/app/modules/core/advertisement/components/reservation/new-reservation/new-reservation.component.html
  src/app/modules/core/advertisement/components/reservation/new-reservation/new-reservation.component.scss
  src/app/modules/core/advertisement/components/reservation/new-reservation/new-reservation.component.spec.ts
  src/app/modules/core/advertisement/components/reservation/new-reservation/new-reservation.component.ts
  src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
  src/app/modules/shared/services/reservation/reservation.service.spec.ts
  src/app/modules/shared/services/reservation/reservation.service.ts
Labels: code review

#233 Feature/issue 174 tenant create the search section
  src/app/modules/core/manager/tenant/components/container/tenant-container.component.html
  src/app/modules/core/manager/tenant/components/container/tenant-container.component.ts
  src/app/modules/core/manager/tenant/components/list/tenant-list.component.html
  src/app/modules/core/manager/tenant/components/list/tenant-list.component.scss
  src/app/modules/core/manager/tenant/components/list/tenant-list.component.ts
  src/app/modules/core/manager/tenant/components/search/tenant-search.component.html
  src/app/modules/core/manager/tenant/components/search/tenant-search.component.scss
  src/app/modules/core/manager/tenant/components/search/tenant-search.component.spec.ts
  src/app/modules/core/manager/tenant/components/search/tenant-search.component.ts
  src/app/modules/core/manager/tenant/tenant.module.ts
  src/app/modules/shared/services/tenant/tenant.service.spec.ts
  src/app/shared/models/landlord.ts
  src/app/shared/models/manager.ts
  src/app/shared/models/mock-data/data.ts
  src/app/shared/models/tenant.ts
  src/app/shared/models/users.ts
Labels: code review

#236 Feature/issue 216 make an advertisement stand up on mouse over
  src/app/modules/core/advertisement/advertisement.module.ts
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.scss
  src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
  src/app/modules/core/advertisement/stand-up.directive.spec.ts
  src/app/modules/core/advertisement/stand-up.directive.ts
Labels: code review

#232 Feature/issue 224 create a reservation component
  src/app/modules/core/manager/reservation/components/container/reservation-container.component.html
  src/app/modules/core/manager/reservation/components/container/reservation-container.component.spec.ts
  src/app/modules/core/manager/reservation/components/container/reservation-container.component.ts
  src/app/modules/core/manager/reservation/components/details/reservation-details.component.html
  src/app/modules/core/manager/reservation/components/details/reservation-details.component.scss
  src/app/modules/core/manager/reservation/components/details/reservation-details.component.spec.ts
  src/app/modules/core/manager/reservation/components/details/reservation-details.component.ts
  src/app/modules/core/manager/reservation/components/list/reservation-list.component.html
  src/app/modules/core/manager/reservation/components/list/reservation-list.component.scss
  src/app/modules/core/manager/reservation/components/list/reservation-list.component.ts
  src/app/modules/core/manager/reservation/reservation-routing.module.ts
  src/app/modules/core/manager/reservation/reservation.module.ts
  src/app/shared/models/mock-data/data.ts
Labels: code review

#218 Feature/issue 173 refactor landlord service
  package-lock.json
  src/app/app.module.ts
  src/app/modules/core/manager/landlord/components/edit/edit.component.html
  src/app/modules/core/manager/landlord/components/edit/edit.component.ts
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.spec.ts
  src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
  src/app/modules/core/manager/landlord/components/search/search.component.spec.ts
  src/app/modules/core/manager/landlord/components/search/search.component.ts
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.html
  src/app/modules/core/manager/landlord/components/view/components/container/container.component.ts
  src/app/modules/core/manager/landlord/services/search.service.spec.ts
  src/app/modules/core/manager/landlord/services/search.service.ts
  src/app/modules/shared/services/landlord/landlord.service.spec.ts
  src/app/modules/shared/services/landlord/landlord.service.ts
Labels: code review
